### PR TITLE
Last arguments must have default values too

### PR DESCRIPTION
**Pull request by dseguy**

### CODE REVIEW

**Comment by mageekguy** [comment]
Test failed, so your PR can not be merged.
If you need help to resolve this, go to IRC on Freenode, channel ##atoum (yep, 2 #, it's not a typo ;)).

**Comment by Hywan** [comment]
@dseguy I have restarted the tests because it should not fail :-/. Your PR seems correct to me.

**Comment by Hywan** [comment]
@dseguy Oh, didn't see your new patch. Sorry.

**Comment by Hywan** [comment]
:+1: for me. @dseguy, please, rebase your PR into a single commit before merging.

**Pull request closed without merging**
