### PR TITLE
Fix #560

### LINKED ISSUE #560: Could not use mock on binded interface on PHP7
I'm working on a PHP7 project. And I facing on a bug on the atoum mock engine. 

I could not mock a simple interface like this:
```php
<?php

namespace MyProject;

interface FooRepositoryInterface
{
    public function load(int $id): Foo;
}
```

When I'm trying do mock it ` new \mock\MyProject\FooRepositoryInterface();`, a fatal error is triggered:
```
==> Error FATAL ERROR in /Users/spy-seth/workspace/atoum-php7-binding-bug/tests/units/FooManager.php on unknown line, generated by file /Users/spy-seth/workspace/atoum-php7-binding-bug/vendor/atoum/atoum/classes/mock/generator.php(200) : eval()'d code on line 2:
Declaration of mock\MyProject\FooRepositoryInterface::load(int $id): mock\MyProject\MyProject\Foo must be compatible with MyProject\FooRepositoryInterface::load(int $id): MyProject\Foo
> There is 1 uncompleted method:
=> MyProject\tests\units\FooManager::test_it_sould_generate_the_mock() with exit code 255:
==> output(0) ""
```

I've made a project example to reproduce the issue: https://github.com/Spy-Seth/atoum-php7-binding-bug. Here a travis build that reproduce the issue: https://travis-ci.org/Spy-Seth/atoum-php7-binding-bug/builds/104898435

### PR DESCRIPTION
**Pull request by GuillaumeDievart**

### CODE REVIEW

**Comment by jubianchi** [comment]
:heart:

**Comment by jubianchi** [comment]
seems good :+1:!

@GuillaumeDievart please can you write a more detail commit message and add the related changelog entry ( bugfix)

@atoum/rms can we have this merged and released by the end of this week ?

**Comment by Hywan** [comment]
@GuillaumeDievart: Need to update the `CHANGELOG.md`.

**Comment by Hywan** [comment]
@jubianchi It's not a bug fix, but we can do an exception if we have enough commits in the pipe. Is it urgent?

**Comment by GuillaumeDievart** [comment]
> please can you write a more detail commit message and add the related changelog entry ( bugfix)

@Hywan @jubianchi Ok

**Comment by Spy-Seth** [comment]
That was fast! :+1:

**Comment by jubianchi** [comment]
@hywan yes it is!

**Comment by Hywan** [comment]
@jubianchi In #560, this issue holds the bug label. Is it a bug or a feature :-)?

**Comment by jubianchi** [comment]
@Hywan the issue (#560) is a bug and the associated PR (#561) its fix.

This is a bug: mocking method with return-type hint is supported since several month (when I actually worked on PHP7 support) but it does only support scalar type-hint which is only 50% of what PHP let us do. I shipped a semi-feature, a buggy feature.

I would argue this is a feature only if atoum would have handled this case gracefully and not thrown the PHP error as is but it's not the case, so there is a bug which is now fixed.

If you d'ont have time to release, fine, let me know and I'll do it ;) but we need this release as more and more tests are written against PHP7.

**Comment by Hywan** [comment]
So it's a bug. I will do the release as soon as this PR is complete.

**Comment by GuillaumeDievart** [comment]
@Hywan I have updated the commit message and the CHANGELOG.md

**Comment by Hywan** [comment]
@jubianchi Can you do the release please? Something unexpected avoid me to do that. Sorry.

**Comment by Hywan** [comment]
@GuillaumeDievart Thanks!

**Comment by GuillaumeDievart** [comment]
> I shipped a semi-feature, a buggy feature.

@jubianchi, not you, but me ... (https://github.com/atoum/atoum/blame/master/classes/mock/generator.php#L610)

**Comment by mikaelrandy** [comment]
[2.5.2 is released](https://github.com/atoum/atoum/releases/tag/2.5.2)

**Comment by jubianchi** [comment]
:+1:

**Comment by Spy-Seth** [comment]
Tested locally it works perfectly :+1: Thank!

**Pull request merged**
