### PR TITLE
feat: Add the dot report

### LINKED ISSUE #743: [RFE] discussion - minimal report format
Hi,

Current  format generate some... _uggly_ output (when run without terminal and with report  into a file)
Ex: https://kojipkgs.fedoraproject.org//work/tasks/5282/22125282/build.log
```
[...........................................................>][  0/420]
[S..........................................................>][  1/420]
[SS.........................................................>][  2/420]
[SSS........................................................>][  3/420]
[SSSS.......................................................>][  4/420]
[SSSSS......................................................>][  5/420]
[SSSSSS.....................................................>][  6/420]
[SSSSSS-....................................................>][  7/420]
[SSSSSS-S...................................................>][  8/420]
...
[SSSSSS-SSSSSSSSSSSSSSSSSSSSSSSSS0SSSSSSSSSSSSSSSSSSSSSSSSSS>][ 59/420]
[...........................................................>]
[...........................................................S][ 60/420]
[...........................................................SS[ 61/420]
[...........................................................SSS[ 62/420]
[...........................................................SSSS[ 63/420]
....
[......._____________________________________________________]SSSSSSS[420/420]
Success (68 tests, 414/420 methods, 2 void methods, 4 skipped methods, 10337 assertions)!
```

This is related to `\r` usage.

It will be nice to have a very minimal which only use `\n`

BTW, after a quick look, it will have to impact the progressBar function, which is consistent (so have to find another way...)

Feedback.

P.S. this also impact output from composer, when composer.json have
```
    "scripts": {
        "test": "vendor/bin/atoum --debug --bootstrap-file tests/bootstrap.php --no-code-coverage --max-children-number 1 -d tests/units",
```

So

```
$ composer test
> vendor/bin/atoum --debug --bootstrap-file tests/bootstrap.php --no-code-coverage --max-children-number 1 -d tests/units

Loading GLPI dataset version 4.2
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Done

> atoum path: /work/GLPI/master/vendor/atoum/atoum/bin/atoum
> atoum version: 3.2.0
> PHP path: /usr/bin/php
> PHP version:
=> PHP 7.0.24 (cli) (built: Sep 26 2017 17:20:11) ( NTS )
=> Copyright (c) 1997-2017 The PHP Group
=> Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
=>     with Zend OPcache v7.0.24, Copyright (c) 1999-2017, by Zend Technologies
> test\units\KnowbaseItem_Item...
[....________________________________________________________][0/4]
[S...________________________________________________________][1/4]
[SS..________________________________________________________][2/4]
[SSS.________________________________________________________][3/4]
[SSSS________________________________________________________][4/4]
...
```

Comment very welcome

### PR DESCRIPTION
**Pull request by jubianchi**
Closes #743 

This PR introduces a new report, the dot report, and a new CLI arguments `--use-dot-report`/`-udr` to enable it.

Here is an example output:

```
$ bin/atoum -udr -f tests/units/classes/test.php
............................................................ [60/65]
.....                                                        [65/65]

Success (1 test, 65/65 methods, 0 void method, 0 skipped method, 872 assertions)!
```

cc @remicollet

### CODE REVIEW

**Comment by remicollet** [comment]
@jubianchi thanks for this, will test it ASAP, before end of week, for now busy with 7.2 in Fedora ;)

**Comment by jubianchi** [comment]
@remicollet Thanks!

**Comment by remicollet** [comment]
Here is a Fedora scratch build of 3.2.0 + this PR
https://kojipkgs.fedoraproject.org//work/tasks/5891/22235891/build.log

This looks perfect ! :)
Thanks

**Comment by Grummfy** [comment]
yeah, nice to hear.
Once again thanks  for your support @remicollet

**Comment by jubianchi** [comment]
Thanks a lot @remicollet!

**Pull request merged**
