### PR TITLE
Prepare 2.0.0 release

### PR DESCRIPTION
**Pull request by mikaelrandy**
As #420 is a BC break update, new major release

### CODE REVIEW

**Comment by mikaelrandy** [comment]
ping @Hywan

**Comment by Hywan** [comment]
@mikaelrandy I agree.

**Comment by mageekguy** [comment]
No BC break if a patch is done : https://github.com/atoum/atoum/issues/426#issuecomment-71679712

**Comment by mikaelrandy** [comment]
As date, no patch is in master : BC break in master.

**Comment by Hywan** [comment]
Hmm, but if we can apply the patch quickly, we avoid a regression :-/.

**Comment by mikaelrandy** [comment]
@Hywan of course. It's what I thought to be done 2 weeks ago.
But, as there is no work on this patch, and a BC break on the master branch, i thought it was not a big deal to create a release with a new major number.

**Pull request merged**
