### PR TITLE
Prepare release 2.3.0

### PR DESCRIPTION
**Pull request by mikaelrandy**
- [x] Update changelog
- [ ] [Create tag](https://github.com/atoum/atoum/wiki/How-to-release-atoum#create-and-push-a-tag)
- [ ] [Generate stubs](https://github.com/atoum/atoum/wiki/How-to-release-atoum#generate-stubs)
- [x] [Create 2.4.0 milestone](https://github.com/atoum/atoum/milestones/2.4.0)

### CODE REVIEW

**Comment by mikaelrandy** [comment]
ping @Hywan

**Comment by jubianchi** [comment]
\o/ let's see if building the phar through travis works!

**Comment by mikaelrandy** [comment]
@jubianchi it's work !
https://github.com/atoum/atoum/releases/tag/2.3.0

**Comment by jubianchi** [comment]
awesome! thanks for the release

**Comment by jubianchi** [comment]
we could also publish the stub automatically

**Comment by mikaelrandy** [comment]
It was the first time i publish the stubs, so i wanted to see all process.
But you're right ! => cf. #513

**Pull request merged**
