### PR TITLE
Add appveyor to run CI on Windows

### PR DESCRIPTION
**Pull request by jubianchi**

### CODE REVIEW

**Comment by Hywan** [comment]
:tada:

**Comment by mikaelrandy** [comment]
capture d ecran 2016-01-20 a 14 35 41
capture d ecran 2016-01-20 a 14 35 49

**Comment by jubianchi** [comment]
@mikaelrandy you should now be able to see the builds ;)

**Comment by mikaelrandy** [comment]
@jubianchi still not

**Comment by jubianchi** [comment]
@mikaelrandy use this link https://ci.appveyor.com/project/jubianchi/atoum

**Comment by mikaelrandy** [comment]
@jubianchi your last link work well

**Pull request merged**
