### PR TITLE
Prepare 2.1.0 release

### PR DESCRIPTION
**Pull request by mikaelrandy**

### CODE REVIEW

**Comment by jubianchi** [comment]
Hi @mikaelrandy !

Can you wait a couple days before releasing the 2.1.0 ? I really would like to merge #459 before we release 

Thanks!

**Comment by mikaelrandy** [comment]
It's not a problem for me, but as the release's rhythm is every 6 weeks, no matter if #459 will be released in the next release, no ?

Is there a reason you want to have #459 in this release specifically ?

**Comment by mikaelrandy** [comment]
@jubianchi i just read your last comment on #459.
The 2.1.0 release will be published on wednesday 8th, so you have 3 days to finish it ;)

**Comment by jubianchi** [comment]
Perfect. I'll make it ready before wednesday ;)

**Comment by jubianchi** [comment]
> Is there a reason you want to have #459 in this release specifically ?

There is no particular reason but I think it's an interesting feature and making it wait 6 more weeks to be tagged would be sad. 
Moreover this feature will let me tag the first version of the extension containing the advanced coverage report.

**Comment by mikaelrandy** [comment]
Updated to include #459 (ping @jubianchi)

I also have correct a little mistake on PR number in changelog ;)

**Comment by jubianchi** [comment]
@mikaelrandy good catch! Everything is ok for me ;)

:shipit:

**Pull request merged**
