### PR TITLE
Autoloader should not try to resolve alias if requested class exists

### PR DESCRIPTION
**Pull request by jubianchi**

### CODE REVIEW

**Comment by Hywan** [comment]
:+1: for me.

**Comment by Hywan** [comment]
@jubianchi Was it a bug? I guess yes.

**Comment by jubianchi** [comment]
@Hywan yes to me it's a bug... a minor one but it exists.

This bug was only present when an external package was using the atoum namespace and only the atoum autoloader was enabled.

**Comment by Hywan** [comment]
So we need a new release :-). I will do that soon.

**Pull request merged**
