### PR TITLE
Quality: Move CS to PSR-2

### PR DESCRIPTION
**Pull request by Hywan**
As discussed in #641, here is a PR that changes CS to PSR-2 and more fixers. The goal immediate goal is to see if anyone agrees with these new CS. If yes, I will update Travis, the documentation, the `README.md` etc.

In addition to PSR-2, we add the following fixers:
  * blankline_after_open_tag,
  * concat_with_spaces,
  * no_blank_lines_after_class_opening,
  * ordered_use,
  * phpdoc_no_access,
  * remove_leading_slash_use,
  * remove_leading_slash_uses,
  * self_accessor,
  * short_array_syntax,
  * spaces_cast,
  * unused_use,
  * whitespacy_lines.

The diff is hard to read because of indentation (tab to space) conversion…

Thoughts?

### CODE REVIEW

**Comment by Hywan** [comment]
Oh, we save 1000 LOC. That's not bad ;-).

**Comment by jubianchi** [comment]
@Hywan could you target the `3.0.0-dev` branch please.

**Comment by Grummfy** [comment]
does we really need to move from tab to space, because if we don't respect totally the psr2, so let's keep it that too?

**Comment by Hywan** [comment]
@Grummfy We will respect PSR-2, so I don't see any reason to keep tabs.
@jubianchi Done.

**Comment by Grummfy** [comment]
@Hywan in your introduction you say "In addition to PSR-2, we add the following fixers:" so we don't respect it if we add some extra ?

**Comment by agallou** [comment]
:+1: (it will maybe more difficult to look into the git history, but I can't see how we could pass that)

**Comment by Hywan** [comment]
@grummfy Adding fixers do not invalid PSR-2. We fully respect PSR-2, and we add extra fixers. This is an addition, not a modification.

@agallou Yup, totally agree. People will blame me a lot I guess… but this is very easy to look at the parent commit in a “git blame view” so…

**Comment by Hywan** [comment]
I guess everything is OK now. CS are checked with Travis (only, not with AppVeyor), `README.md`, `CONTRIBUTING.md` and `FAQ.md` have been updated too.

Ready for a review.

**Comment by Hywan** [comment]
Please, can we review this PR? The more we have conflicts, the more it's hard to maintain :-).

**Comment by agallou** [comment]
if we want to use the same settings on extensions, how could we centralize those settings ?

**Comment by Hywan** [comment]
@agallou @jubianchi has setup an account on style CI, maybe it's the solution.

**Comment by Hywan** [comment]
Sorry for the push force but I had no choice. I have restarted the PR based on a refresh `3.0.0-dev` branch. I hope I didn't miss any commit (resolving merge was impossible, I basically run php-cs-fixer and then I have cherry-pick interesting commits by hand that was related to specific file —like `README.md`, `CONTRIBUTING.md`, `.travis.yml` etc.—).

Hope it's good now!

**Comment by Hywan** [comment]
Yeah, it's green :-].

**Comment by mageekguy** [comment]
What is the technical/functional value of this PR ?
@Hywan you said yourself that it's a bad move because diff will became a PITA.
So, the only value is a major drawback, in my opinion.
Moreover, it seems to me that you merge this PR without a consensus in comments…
You said "The goal immediate goal is to see if anyone agrees with these new CS" but nobody said "i'm agree with that, go ahead, man!".

**Comment by Grummfy** [comment]
I don't understand why it's merged too... but ok, it's too late

**Comment by Hywan** [comment]
@mageekguy @Grummfy Yes, nobody have replied here, but @jubianchi, @agallou and I have discussed about it during the ForumPHP (yesterday nigth and today), and we were all agree to merge it. Also, @jubianchi and @mikaelrandy has contributed to the PR, so this is a +1.

@mageekguy The big promise behind PSR-2 is that it will increase contributions. This is why Hoa has moved to PSR-2 too. This is **a big lie**. However, majority of PHP developers nowadays are using this convention, and this is easier to read and to write. Today, *we* are maintaining atoum code base and it is easier for us to review, maintain and develop new features with the same conventions than everyone use and than we use daily. Yes, the diff is hard to read and `git blame` will hate me a lot, but this is a little needle compared what it offers to us. Nobody said “Go ahead” *here*, but they said it in IRL (they will confirm it here I suppose), but nobody said the opposite, aka “Nooo, please noooo!”. This PR is opened since 22 days, targeting the `3.0.0-dev` branch. The more we wait, the more it is hard to maintain.

@mageekguy Now, you just arrived to the lobby in the hotel and I just saluted you, so I guess we will continue this discussion in IRL ;-).

❤️

**Comment by stephpy** [comment]
@Hywan 👍 ❤️

**Pull request merged**
