### PR TITLE
Make the autoloader handle traits

### PR DESCRIPTION
**Pull request by jubianchi**

### CODE REVIEW

**Comment by jubianchi** [comment]
Once merged, this PR should be backported into the `1.x` branch and we should issue a `1.3.0` release.

**Comment by Hywan** [comment]
If ony we should have [`Hoa\Consistency`](http://central.hoa-project.net/Resource/Library/Consistency) '^^.

**Comment by Hywan** [comment]
:+1: for me. Ready to merge? I can do the merge and the release today.

**Comment by Hywan** [comment]
I can do the 2.5.1 release. Then we will see for the backport as decoupled process.

**Comment by jubianchi** [comment]
ready for the release (2.5.1)

**Comment by Hywan** [comment]
I am starting the release.

**Comment by mikaelrandy** [comment]
Why this is a bugfix ?

**Comment by jubianchi** [comment]
@mikaelrandy not really a bug but not really a feature so to make the release faster, it has been tagged as a patch release ;)

**Comment by Hywan** [comment]
(release done by the way ;-))

**Comment by Hywan** [comment]
https://github.com/atoum/atoum/releases/tag/2.5.1

**Comment by Hywan** [comment]
@jubianchi Actually, it's a bug for some extensions. So it's a bug :-p.

**Comment by jubianchi** [comment]
@Hywan not a bug in any extension: you added a trait but our autoloader did not handle them. Not a bug but a missing feature.

Every functionnality of the autoloader is correct before this patch.

**Comment by mikaelrandy** [comment]
@jubianchi @Hywan i can understand we want to release faster as the initial idea behind our calendar based release rythme was chosen to don't interfere with the rolling release.
But it seems the versioned releases are now far more used.

So i can understand we want to release a new feature behind our planned releases, but i am sceptical on release bug release for this.

**Pull request merged**
