### PR TITLE
Release 2.4.0

### PR DESCRIPTION
**Pull request by mikaelrandy**

### CODE REVIEW

**Comment by mikaelrandy** [comment]
There is failure with PHP 7 :/

Any clue @jubianchi ?

**Comment by Hywan** [comment]
@mikaelrandy Wait wait! The 2.4.0 is not ready yet. That's why I didn't make the release myself.

**Comment by Hywan** [comment]
@mikaelrandy Check this out https://github.com/atoum/atoum/milestones/2.4.0.

**Comment by mikaelrandy** [comment]
@Hywan ok. For previous releases, all opened issues/PRs was affected to next release.
So i think it would be identical for this release.

**Comment by Hywan** [comment]
@mikaelrandy I know few of them are closed to be fixed.

**Comment by jubianchi** [comment]
@mikaelrandy @Hywan I think we can postpone remaining issues. 

I'm working on failing tests: seems like they were introduced with the update of php :/

**Comment by mikaelrandy** [comment]
@jubianchi @Hywan ok for me. i propose to create next milestone, not automatically affect all remaining issues to this one, and just affect ones we **really** want to see in next release.Ok for you ?

In any case, i will wait for tests to be back on green before release v2.4.0

**Comment by jubianchi** [comment]
@mikaelrandy https://github.com/mikaelrandy/atoum/pull/3 here is the PR on your branch

**Comment by jubianchi** [comment]
@mikaelrandy gogogo rebase ;)

**Comment by Hywan** [comment]
:racehorse:

**Comment by jubianchi** [comment]
:tada:

**Comment by Hywan** [comment]
:tada:

Congrats everyone.

**Pull request merged**
