### PR TITLE
Update atoum's phar through github releases

### PR DESCRIPTION
**Pull request by jubianchi**
This allows phar users to do :

```
php atoum.phar --github-update
```

The phar will then use the Github Releases API to find the latest release, check if it's newer than the actual phar, download the phar from github an update everything locally.

### CODE REVIEW

**Comment by Grummfy** [comment]
thanks

:+1:

**Comment by Grummfy** [comment]
will help for #404

**Comment by jubianchi** [comment]
not found :p

**Comment by Grummfy** [comment]
and #383 and #504

**Comment by mikaelrandy** [comment]
:

**Comment by Hywan** [comment]
Why `--github-update` and not override `--update`?

**Comment by jubianchi** [comment]
this PR was not ready to be merged. It has not been tested in production yet!

**Comment by Mandragora2** [comment]
@jubianchi fail ?

**Comment by Hywan** [comment]
@jubianchi I tested it and it worked great.

**Comment by jubianchi** [comment]
@Hywan fine thanks!

We'll have to handle some error (http errors) and write some tests.

**Comment by Hywan** [comment]
@jubianchi What about `--github-update` vs. `--update`. This creates another issue because the PHAR on downloads.atoum.org is not up-to-date. I guess official PHAR are hosted on Github, so why not merging these too options?

**Comment by jubianchi** [comment]
@Hywan, merging the two options resuires a more clever update strategy: atoum should try several mirrors until it finds one available and downloads the phar from it.

Currently, the process is a bit dumb and rely on the user to make a decision.

**Comment by Hywan** [comment]
@jubianchi Fine… but `--update` is still broken since downloads.atoum.org is broken. Can we do a redirect on downloads.atoum.org instead?

**Pull request merged**
