### PR TITLE
make PHAR link point to a recent version

### PR DESCRIPTION
**Pull request by CedCannes**
I followed the old link pointing to download.atoum.org that contains version : nightly - 2416-201402121146 of the PHAR and I couldn't use atoum correctly with the new features listed in her pretty documentation. 
I think it is detrimental for those who want to discover atoum
as mentioned in #586

### CODE REVIEW

**Comment by Hywan** [comment]
Why can't we use `latest` instead of `2.6.0` in the URL?

**Comment by jubianchi** [comment]
@Hywan download URLs are not allowed to use the `latest` word :/

**Comment by Grummfy** [comment]
This is why I have made a script a long time ago to get the last version.

For me this issue is the reflect of what I insist since more than a year to fix this issue. A simple redirection will solve the problem...

**Comment by mageekguy** [comment]
Hi folks,

I think that the problem is… me ;)
It seems to me that in galaxy far far far away, someone send to me the URL which will be used to redirect to the right version of the PHAR, but i have forget to do the redirection…
So, if someone send me (again) the URL… maybe i will not forget to configure the legacy web server accordingly!

**Comment by Hywan** [comment]
cc @Grummfy

**Comment by Grummfy** [comment]
I have no link ;) I have create a file to redirect people and say that we probably need a cache or something like that....

https://gist.github.com/Grummfy/2f040c293dce5109810f

but that's all. So if you want I can create a better script with some cache and give it to mageeguy to do the job, if t's ok for you.

**Pull request merged**
