### PR TITLE
Add travis configuration to deploy phar for tags

### PR DESCRIPTION
**Pull request by jubianchi**
This will allow us to automatically deploy the phar as a release artifact each time a tag is created.

You can see a sample green build here : https://travis-ci.org/jubianchi/atoum/jobs/82954506#L1505
And the associated release with the phar here : https://github.com/jubianchi/atoum/releases/tag/9.9.12

### CODE REVIEW

**Comment by mikaelrandy** [comment]
:+1: 

Mais c'est normal l'API key versionnée ?

**Comment by jubianchi** [comment]
@mikaelrandy it's encrypted so yes totally fine ;)

**Comment by Hywan** [comment]
@jubianchi :+1: for me. I think this is not needed to include a line in the `CHANGELOG.md` for that. I updated the wiki consequently: https://github.com/atoum/atoum/wiki/How-to-release-atoum.

**Comment by Hywan** [comment]
@jubianchi What about stubs? Should we open another issue/PR?

**Comment by jubianchi** [comment]
@hywan stubs are released on their own and we produce no artifact for them. the only thing we should do there is to put a tag each time we release atoum

**Pull request merged**
