### PR TITLE
Fix PHP 8.1 return type deprecation errors

### PR DESCRIPTION
**Pull request by cedric-anne**
Fixes `ArrayAccess`, `Countable` and `IteratorAggregate` implementations.

It removes the fluent logic on `ArrayAccess` implementations, so it may introduce BC breaks.

### CODE REVIEW

**Comment by Grummfy** [comment]
Honestly, it's why I need time to check it ;)

Using a two steps process, could indeed be the right path to make it properly done.

If you see some other element to break feel free to prepare it for a V5 ;)

**Comment by villfa** [comment]
Hi @cedric-anne,
There is also an implementation of `OuterIterator` here: https://github.com/atoum/atoum/blob/master/classes/iterators/recursives/atoum/source.php
I think it's related to the seg fault in 8.1.

**Comment by cedric-anne** [comment]
Hi @villfa 

I think all of them are fixed now.

I executed this simple script in atoum roor dir to detect them:
```php
spl_autoload_register(
    function ($class) {
        if (!preg_match('/^atoum\\\\/', $class)) {
            return;
        }
        include 'classes/' . implode('/', explode('\\', preg_replace('/^atoum\\\\atoum\\\\/', '', $class))) . '.php';
    }
);

$dir_iterator = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator(__DIR__ . '/classes'),
    RecursiveIteratorIterator::SELF_FIRST
);
foreach ($dir_iterator as $file) {
    if ($file->getExtension() !== 'php') {
        continue;
    }
    require_once $file->getRealPath();
}
```

**Comment by cedric-anne** [comment]
> I think it's related to the seg fault in 8.1.

Segfault is still present :/.

**Pull request merged**
