### PR TITLE
feat(script) Align options to the left, and increase contrast

### LINKED ISSUE #760: CLI: Help text options are hard to read
I know this is my opinion, but I find the center-alignment of the help text options (when running `atoum --help`) difficult to read. It's also a pattern I've never seen in other CLI tools which are typically left-aligned and wrap in columns.

The CLI help text also has no maximum line-length and when it wraps it's hard to read. It would be better to wrap within columns.

Finally, the default colors for the options have poor contrast on a black background. The common pattern I've seen in other CLI tools is to not colorize the help text.

For example here's my help text:

screen shot 2017-10-09 at 7 00 45 pm

Compared to, for example, Jest:

screen shot 2017-10-09 at 7 01 40 pm

### PR DESCRIPTION
**Pull request by Hywan**
Fix #760.

Result:
screen shot 2017-10-10 at 10 54 22

Thoughts @sirbrillig?

### CODE REVIEW

**Comment by vonglasow** [comment]
@Hywan seems ok, have you try on small screen also to see if it looks well also ? If yes good for me.

**Comment by Hywan** [comment]
@vonglasow On a small screen, it looks waayyyyy better than previously :-).

**Comment by Hywan** [comment]
Oops, too late…

**Comment by jubianchi** [comment]
@Hywan please, open a new PR to fix the tests and the color.

**Comment by Hywan** [comment]
@jubianchi Sure!

**Comment by Hywan** [comment]
@jubianchi https://github.com/atoum/atoum/pull/772

**Comment by Hywan** [comment]
@mageekguy Agree, and a low contrast impact everyone. Now we have a much better contrast, that's one step foward.

**Pull request merged**
