### PR TITLE
Typehint atoum test class and asserters

### LINKED ISSUE #231: Add @method doc annotation to atoum\test
The base test class could have annotations to help IDEs autocomplete asserters etc.

The aws php sdk does the same thing as it also uses __call (guzzle thing). https://github.com/aws/aws-sdk-php/blob/master/src/Aws/S3/S3Client.php

### PR DESCRIPTION
**Pull request by adrienbrault**
Fixes #231

### CODE REVIEW

**Comment by gauthier** [comment]
I agree that lack of code-insight, at least for the first level of asserter calling, is a mess!

There is a much easier way that @srogier proposed to make IDEs like PhpStorm aware of magic method calls: the @method PHPDoc tag. I wish they've been added in Atoum source files directly, but... well, I won't troll (now) about comments absence in Atoum ;)

So, I made a very simple thing for my own usage: an intermediate class between atoum\test and my actual test cases, in which I added those tags.

Feel free to have a look, and correct/complete it since for many asserters, I base the @method comments only on the asserters name...

You can test it by requiring objective-php/atoum-extension with composer and then extend `ObjectivePHP\AtoumExtension\AtoumTestCase` instead of `mageekguy\atoum\test`

Repository home is on https://github.com/objective-php/atoum-extension

PR are welcome ;)

**Comment by jubianchi** [comment]
I just release this: https://github.com/atoum/stubs

This is a full set of stubs for atoum. It may provide code-completion for everything that is commonly used by test writers.

ping @JEDIBC

**Comment by Hywan** [comment]
:+1:

**Comment by jubianchi** [comment]
Closing this as we now have atoum/stubs

**Comment by Hywan** [comment]
:+1:

**Pull request closed without merging**
