### PR TITLE
remove iteratorAggregate interface from directory iterator factory

### PR DESCRIPTION
**Pull request by pschultz**
`mageekguy\atoum\iterators\recursives\directory\factory` doesn't really implement `IteratorAggregate`

### CODE REVIEW

**Comment by Hywan** [comment]
Hello :-),

As far as I can see, `factory` correctly implements `IteratorAggregate` with the `getIterator` method. Why HHVM is complaining?

**Comment by pschultz** [comment]
`factory::getIterator` takes an argument, `IteratorAggregate::getIterator` does not. That PHP isn't complaining is a bug in PHP. If IteratorAggregate was a userland interface it blow up the same as HHVM.

**Comment by Hywan** [comment]
Indeed, that's correct!

**Comment by jubianchi** [comment]
this should also be fixed in #451

**Comment by Hywan** [comment]
Is it already fixed in #451 though? If no, I am asking @jubianchi to merge it in #451.

**Comment by Hywan** [comment]
@jubianchi Ahhh, a second too late!

**Comment by jubianchi** [comment]
@Hywan i'll review my code  if this is not fixed I'll merge this patch in #451 ;)

**Comment by pschultz** [comment]
#451 contains a similar patch. See discussion on #480

**Comment by jubianchi** [comment]
closing in favor of #451

**Comment by Hywan** [comment]
This issue is still not closed (https://github.com/atoum/atoum/blob/master/classes/iterators/recursives/directory/factory.php#L62) and HHVm is still complaining.

**Pull request closed without merging**
