### PR TITLE
Fix issue #98: "Can't build phar on windows"

### PR DESCRIPTION
**Pull request by kao98**
Tried to fix the issue #98. Hope this is acceptable to you!?

### CODE REVIEW

**Comment by kao98** [comment]
Up!?

**Comment by jubianchi** [comment]
hi @kao98!

i really want to merge your patch back into master but before that I would like to have some feedback from other windows users  

Anyone @atoum/all ?

**Comment by kao98** [comment]
I know that :-/

It seems there're not a lot of contributors running on windows, maybe the best feedbacks could be to accept the pull request and wait for some issues to be opened!?

This pull request fix a non-usable feature on windows. So bad to block it like that.

**Comment by mikaelrandy** [comment]
@jubianchi i agree with @kao98 : if this PR do not break something on Unix-like system, we should merge it.
Today, phar build is broken on windows, and it's a major problem for windows adoption of atoum (even if this population is not the major part of atoum users)

**Comment by jubianchi** [comment]
Closing this one in favor of https://github.com/atoum/atoum/pull/533.

THanks @kao98!

**Pull request closed without merging**
