### PR TITLE
Remove dependency on ext-session

### PR DESCRIPTION
**Pull request by jubianchi**

### CODE REVIEW

**Comment by Hywan** [comment]
ping?

**Comment by Grummfy** [comment]
pong?

**Comment by shouze** [comment]
ping?

would be nice to merge it, as I've built php with sessions disabled and composer installation of atoum comlains ;)

**Comment by Hywan** [comment]
Closed in favor or #731.

**Comment by Hywan** [comment]
@shouze `master` contains your fix.

**Comment by shouze** [comment]
@Hywan thank you so much 🚀

**Pull request closed without merging**
