### PR TITLE
atoum-phpunit bridge

### PR DESCRIPTION
**Pull request by jubianchi**
This PR is a work in progress. It aims to implement a bridge allowing atoum to run PHPUnit tests.
Currently, this supports the following from PHPUnit:
## Assertions

<table>
<tr>
<td>assertFalse</td><td>assertTrue</td><td>assertNull</td><td>assertNotNull</td>
</tr>
<tr>
<td>assertEquals</td><td>assertNotEquals</td><td>assertContains</td><td>assertNotContains</td>
</tr>
<tr>
<td>assertSame</td><td>assertInstanceOf</td><td>assertNotInstanceof</td><td>assertArrayHasKey</td>
</tr>
<tr>
<td>assertCount</td><td>assertFileExists</td><td>assertFileNotExists</td><td>assertStringStartsWith</td>
</tr>
<tr>
<td>assertAttributeEquals</td>
</tr>
</table>

## Mock

<table>
<tr>
<td>getMock</td><td>getMockForAbstractClass</td><td>getMockBuilder</td>
</tr>
</table>

### Expectations

<table>
<tr>
<td>expects</td><td>any</td><td>exactly</td><td>once</td><td>atLeastOnce</td><td>at</td><td>never</td>
</tr>
<tr>
<td>with</td><td>equalTo</td><td>identicalTo</td>
</tr>
</table>

### Definition

<table>
<tr>
<td>will</td><td>returnValue</td><td>returnVallback</td><td>onConsecutiveCalls</td><td>throwException</td>
</tr>
</table>

So basically, something like this will work with atoum:

``` php
<?php
$mock = $this->getMock('\\Foo\\Bar');
$mock
    ->expect($this->any())
    ->method('baz')
    ->with('arg1', 'arg2')
    ->will($this->returnValue('returnval'))
;

//...
```
### Misc.

<table>
<tr>
<td>@group</td><td>markTestSkipped</td><td>fail</td>
</tr>
</table>

## How to use:

I ported two test suites as examples:
- Composer
  - jubianchi/composer: https://github.com/jubianchi/composer/compare/composer:master...master
  - travis builds: https://travis-ci.org/jubianchi/composer
- Twig
  - jubianchi/Twig: https://github.com/jubianchi/Twig/compare/fabpot:master...master
  - travis builds: https://travis-ci.org/jubianchi/Twig

Enabling atoum on a PHPUnit test suite is quite simple:
- edit your `composer.json` to point to this branch: https://github.com/jubianchi/composer/compare/composer:master...master#diff-1
- Include atoum in your bootstrap : https://github.com/jubianchi/composer/compare/composer:master...master#diff-176
  I'm still working on this as there are some bugs to fix (like the one making composer's build fail on `5.4` and `5.5`)
- Edit your test (just a little :wink:): https://github.com/jubianchi/composer/compare/composer:master...master#diff-165
  - include your bootstrap file to get autorunner support (`php path/to/phpunit/test/file.php`). This is optionnal.
  - short-circuit the `setUp`/`tearDown` PHPUnit methods as they have a different meaning in atoum
  - inside a test class, if several test methods share resources, do not forget to enable the `inline` engine with the `@engine` annotation: https://github.com/jubianchi/composer/compare/composer:master...master#L167R27 

Sometimes, tests need some other changes to work. Ideally, this should not happen (or only in some rare cases).

Feel free to review everything, perhaps test it, and let me know what you think about this tool ;)

### CODE REVIEW

**Comment by Grummfy** [comment]
@jubianchi tu en est où? Que reste-il a faire a ce sujet? faut-il que l'on test sur des projets?

**Comment by jubianchi** [comment]
@Grummfy I would have to ebase the branch, clean it a bit and migrate some kind of migration guide then you'll be able to test.

This branch is really interesting but to make it work I really need users feedback. If you think you'll be able to test when I push new things I can work on this feature again.

**Comment by Grummfy** [comment]
I think this can help people to use atoum. So if I can help and run some test on other project, I will be happy to do it.

**Comment by jubianchi** [comment]
@Grummfy I rebase the branch, if you want to run some tests, just go ;)

**Comment by Hywan** [comment]
ping?

**Comment by jubianchi** [comment]
@Hywan **I need feedback**

**Comment by Hywan** [comment]
@jubianchi I made a promotion on Twitter: https://twitter.com/atoum_org/status/666147763755839488.

**Comment by Hywan** [comment]
@jubianchi Nevertheless, might it land into an extension instead of the core?

**Comment by jubianchi** [comment]
@Hywan I was thinking of extracting this to an ext. but it still requires some work in the core.

👍

**Comment by engine-xx** [comment]
Pong?

 

Giuseppe

 

Da: Ivan Enderlin [mailto:notifications@github.com] 
Inviato: domenica 15 novembre 2015 22:59
A: atoum/atoum
Cc: engine-xx
Oggetto: Re: [atoum] atoum-phpunit bridge (#227)

 

ping?

**Comment by Grummfy** [comment]
I try to do it on https://github.com/Grummfy/Aura.Di/tree/2.x-atoum-tests  => https://travis-ci.org/Grummfy/Aura.Di/branches
* define a .atoum.php file with an autoloader
* use composer dependency for atoum with phpunit bridge
* It  could help to have a definition of "short-circuit the setUp/tearDown PHPUnit methods as they have a different meaning in atoum" so I just make it public... 

To improve this project, here is some clue:
* we could give a configuration file to help people having by default inline engine (with a comment in this file to say it's forced to help checking validity)
* we should also give a configuration that will help people with naming convention ;) Most of the time they use same namespace but with Test as pre or postfix in the name of the class. A configuration file with some comment for most of naming convention will be OK
* we should also give an easy way to give some "base test class" not simple alias but to set some configuration for all of they test. Because in a normal situation they probably don't need it (they don't change everything), but in the case where they migrate, it could help to have a file with a class called "PHPUnit_Framework_TestCase" that they can change instead of using the given from this work.

**Comment by Grummfy** [comment]
est-ce encore relevant avec https://github.com/atoum/phpunit-extension/ ?

**Comment by Hywan** [comment]
Closed in favor or the PHPUnit extension.

**Pull request closed without merging**
